---
title: "Education"
---
        
        
## PhD
**Texas A&M University**     
**Department of Horticultural Sciences**   
  
**Dissertation title:** Genetic Analysis and QTL Discovery in Tetraploid Garden Roses: A Study of Disease and Horticultural Traits  
  

**Abstract:** Currently, there are only three high density single-nucleotide polymorphism (SNP) based linkage maps available in tetraploid garden and cut flower roses (Rosa spp.). Two populations, Rosa L. ‘ORAfantanov’ (Stormy Weather™) x Rosa L. ‘Radbrite’ (Brite Eyes™) (SWxBE) and Rosa L. ‘Radbrite’ (Brite Eyes™) x Rosa L. ‘BAIgirl’ (Easy Elegance® My Girl) (BExMG), were genotyped using the WagRhSNP 68K Axiom SNP array and evaluated for the incidence of rose rosette disease (caused by rose rosette virus), black spot of rose (*Diplocarpon rosae* F.A. Wolf), and cercospora leaf spot (*Cercospora rosicola* Pass.) and assessed for defoliation, flowering intensity, plant size, and apical dominance. The clonally propagated populations and were evaluated in Somerville, TX, Overton, TX, and Crossville, TN. Linkage maps were created and quantitative trait loci (QTL) interval mapping and genome-wide association analysis (GWAS) were used to identify QTL. QTL for resistance were discovered for rose rosette disease on LGs 3 and 5, black spot on LGs 3, 5, and 7, cercospora leaf spot on LGs 1, 4, and 5, and for defoliation on LGs 3, 5, and 7. We discovered a cluster of QTL for black spot, cercospora, and defoliation near a black spot resistance locus, Rdr4, on LG 5. QTL for flower intensity were found on LGs 1, 3, 4, and 5, and for plant size (length, width, height, primary stem lengths) on LGs 1, 3, 5, and 6, for plant shape on LGs 3 and 7, and stem color on LG 6. We discovered plant architecture related QTL are near the everblooming gene, *RoKSN*, on LG 3, floral activation gene, *RoFT*, on LG4, GA signaling gene, *RoSLEEPY*, on LG 6, and a gene involved in deactivation of GA, *RoGA2ox*, on LG 5. In addition to QTL discovery, we were able to isolate 18 progeny in the BExMG family that carried 2 resistance alleles against black spot and one resistance allele for cercospora leaf spot for use in future breeding.


## Master's
**Auburn University**  
**Department of Horticulture**   
  
**Thesis Title:** Investigating Uses for Industrial Sweetpotato in Addition to Ethanol Production to Establish Industrial Sweetpotato as a Sustainable Crop in the Southeastern United States. 
  
**Abstract:** Field studies were conducted evaluating the effect of nitrogen fertilizer on yield, crude protein (CP), total digestible nutrients (TDN), and acid detergent fiber (ADF) of industrial sweetpotato tuberous roots (*Ipomea batatas*) cultivar ‘Xushu.’ After harvest, sweetpotatoes were dried and submitted for feed analysis for possible use as animal feed. Sweetpotatoes were also fermented and the fermentation by-product was submitted for feed analysis for possible use as protein supplement in animal feed. Feed analysis revealed that the energy (TDN) levels of fresh sweetpotato were similar to corn, the current standard energy component in commercial livestock feeds. Feed analysis of sweetpotato fermentation byproduct revealed CP levels that were half to two thirds the amount in soybean. The TDN and CP levels in this research suggests that fresh industrial sweetpotato tuberous roots could be used as an energy source in livestock feed and industrial sweetpotato fermentation by-product can be used as a protein source in livestock feed.
  
## Undergraduate  
Auburn University
Department of Horticulture